build:
  stage: build
  image: dock.mau.dev/tulir/gomuks-build-docker/android:linux-amd64
  tags:
  - linux
  - amd64
  variables:
    SECURE_FILES_DOWNLOAD_PATH: "./"
  before_script:
  - curl --silent "https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer" | bash
  script:
  - ./gradlew assembleRelease
  - mv ./app/build/outputs/apk/release/app-arm64-v8a-release.apk gomuks-android-arm64-v8a.apk
  - mv ./app/build/outputs/apk/release/app-x86_64-release.apk gomuks-android-x86_64.apk
  after_script:
  - rm -f release-keystore.jks
  artifacts:
    paths:
    - gomuks-android-*.apk
